// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "APPSYNC_GRAPHQL_ENDPOINT": "<put appsync endpoint here>",
    "APPSYNC_AWS_REGION": "<put region here>",
    "APPSYNC_AUTHENTICATION_TYPE": "API_KEY",
    "APPSYNC_API_KEY": "<put api key here>",
};

export default awsmobile;